language: python
cache: pip
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - "pip install -r requirements.txt"
  # Fix python 3.5 issue with pytest
  - "pip install pytest>=2.7.3 --upgrade"
  - "pip install ."
script: py.test testing
